# Generated by Django 3.1.5 on 2021-01-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=20)),
                ('option2', models.CharField(max_length=20)),
                ('option3', models.CharField(max_length=20)),
                ('count1', models.PositiveSmallIntegerField(default='0')),
                ('count2', models.PositiveSmallIntegerField(default='0')),
                ('count3', models.PositiveSmallIntegerField(default='0')),
            ],
        ),
    ]
